# B3DV Game Settings
render_distance=64.0
max_fps=0 # 0 means unlimited
nickname=Player
clouds_enabled=true
compass_enabled=false
clouds_render_distance=509.1
language=en

font_family=Inter
font_variant=Inter_28pt-Light.ttf
